version: '3'

services:
  nginx:
    image: 'nginx:stable'
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  php:
    build:
      context: ./
      dockerfile: php.dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"

  node:
    image: node:18-alpine
    volumes:
      - ./:/var/www/html
    build:
      context: ./
      dockerfile: node.dockerfile
