name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Setup Enviroment
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3.0"
      - name: Install Packages
        run: composer install --no-dev
      - name: Deploy to Server
        uses: ngocquyhoang/deploy@laravel
        with:
          user: 'user'
          host: '127.0.0.1'
          port: '8080'
          path: '/'
          owner: 'owner'
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
